[2025-07-13T16:10:24.215+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_market_data.transform_market_data manual__2025-07-13T16:10:16.601820+00:00 [queued]>
[2025-07-13T16:10:24.256+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_market_data.transform_market_data manual__2025-07-13T16:10:16.601820+00:00 [queued]>
[2025-07-13T16:10:24.256+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-13T16:10:24.408+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_market_data> on 2025-07-13 16:10:16.601820+00:00
[2025-07-13T16:10:24.462+0000] {standard_task_runner.py:60} INFO - Started process 1084 to run task
[2025-07-13T16:10:24.475+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'transform_market_data', 'transform_market_data', 'manual__2025-07-13T16:10:16.601820+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/transform_market_data_dag.py', '--cfg-path', '/tmp/tmp8omn83y2']
[2025-07-13T16:10:24.484+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask transform_market_data
[2025-07-13T16:10:24.860+0000] {task_command.py:423} INFO - Running <TaskInstance: transform_market_data.transform_market_data manual__2025-07-13T16:10:16.601820+00:00 [running]> on host 26c08c9ca2cf
[2025-07-13T16:10:25.073+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mark' AIRFLOW_CTX_DAG_ID='transform_market_data' AIRFLOW_CTX_TASK_ID='transform_market_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T16:10:16.601820+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T16:10:16.601820+00:00'
[2025-07-13T16:10:25.160+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-07-13T16:10:26.308+0000] {warnings.py:109} WARNING - /opt/***/dags/transform_market_data_dag.py:16: UserWarning: Polars found a filename. Ensure you pass a path to the file instead of a python file object when possible for best performance.
  df = pl.read_parquet(obj["Body"]).to_pandas()

[2025-07-13T16:10:26.589+0000] {logging_mixin.py:188} INFO - Index(['('close', 'spy')', '('high', 'spy')', '('low', 'spy')',
       '('open', 'spy')', '('volume', 'spy')', 'datetime'],
      dtype='object')
[2025-07-13T16:10:26.604+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_market_data_dag.py", line 24, in transform_yfinance_data
    df = df.drop_nulls()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'drop_nulls'
[2025-07-13T16:10:26.717+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=transform_market_data, task_id=transform_market_data, execution_date=20250713T161016, start_date=20250713T161024, end_date=20250713T161026
[2025-07-13T16:10:26.799+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task transform_market_data ('DataFrame' object has no attribute 'drop_nulls'; 1084)
[2025-07-13T16:10:26.887+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-13T16:10:27.077+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
