[2025-07-19T14:43:43.091+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T14:38:33.982679+00:00 [queued]>
[2025-07-19T14:43:43.093+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T14:38:33.982679+00:00 [queued]>
[2025-07-19T14:43:43.093+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-19T14:43:43.097+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_features> on 2025-07-19 14:38:33.982679+00:00
[2025-07-19T14:43:43.099+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2025-07-19T14:43:43.101+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'validate_features', 'manual__2025-07-19T14:38:33.982679+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpkudc9m1v']
[2025-07-19T14:43:43.102+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask validate_features
[2025-07-19T14:43:43.116+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.validate_features manual__2025-07-19T14:38:33.982679+00:00 [running]> on host 78a06dccabbd
[2025-07-19T14:43:43.143+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='validate_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T14:38:33.982679+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T14:38:33.982679+00:00'
[2025-07-19T14:43:43.161+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-19T14:43:43.162+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-19T14:43:43.162+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:43:43.162+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:43:43.175+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-19T14:43:43.176+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-19T14:43:43.176+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:43:43.176+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:43:43.176+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:43:43.184+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 96, in validate_features
    pandas_df = pl.read_parquet(feature_path).to_pandas()
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/io/parquet/functions.py", line 209, in read_parquet
    return lf.collect()
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 2053, in collect
    return wrap_df(ldf.collect(callback))
FileNotFoundError: No such file or directory (os error 2): /tmp/features.parquet
[2025-07-19T14:43:43.189+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=build_ml_features, task_id=validate_features, execution_date=20250719T143833, start_date=20250719T144343, end_date=20250719T144343
[2025-07-19T14:43:43.192+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 132 for task validate_features (No such file or directory (os error 2): /tmp/features.parquet; 92)
[2025-07-19T14:43:43.203+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T14:43:43.208+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
