[2025-07-19T22:26:12.054+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T22:26:04.665166+00:00 [queued]>
[2025-07-19T22:26:12.057+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T22:26:04.665166+00:00 [queued]>
[2025-07-19T22:26:12.057+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-19T22:26:12.060+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_features> on 2025-07-19 22:26:04.665166+00:00
[2025-07-19T22:26:12.063+0000] {standard_task_runner.py:60} INFO - Started process 143 to run task
[2025-07-19T22:26:12.065+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'validate_features', 'manual__2025-07-19T22:26:04.665166+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmplf2pc7rw']
[2025-07-19T22:26:12.065+0000] {standard_task_runner.py:88} INFO - Job 185: Subtask validate_features
[2025-07-19T22:26:12.080+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.validate_features manual__2025-07-19T22:26:04.665166+00:00 [running]> on host bc2a27ae9be1
[2025-07-19T22:26:12.106+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='validate_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T22:26:04.665166+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T22:26:04.665166+00:00'
[2025-07-19T22:26:12.126+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-19T22:26:12.127+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-19T22:26:12.128+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T22:26:12.128+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T22:26:12.141+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-19T22:26:12.142+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-19T22:26:12.143+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T22:26:12.143+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T22:26:12.143+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T22:26:12.185+0000] {validator.py:1461} INFO - 	12 expectation(s) included in expectation_suite.
[2025-07-19T22:26:12.255+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T22:26:12.255+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T22:26:12.256+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 3776.95it/s]
[2025-07-19T22:26:12.270+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 139.70it/s] 
[2025-07-19T22:26:12.270+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 205.29it/s]
[2025-07-19T22:26:12.283+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 107.61it/s]
[2025-07-19T22:26:12.288+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 490.54it/s]
[2025-07-19T22:26:12.299+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 368.20it/s]
[2025-07-19T22:26:12.310+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1134.06it/s]
[2025-07-19T22:26:12.315+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1047.75it/s]
[2025-07-19T22:26:12.315+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1045.74it/s]
[2025-07-19T22:26:12.315+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1043.44it/s]
[2025-07-19T22:26:12.500+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 110, in validate_features
    docs_url = f"https://{os.environ['CF_GE_DOCS_DOMAIN']}/index.html"
NameError: name 'os' is not defined
[2025-07-19T22:26:12.505+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=validate_features, execution_date=20250719T222604, start_date=20250719T222612, end_date=20250719T222612
[2025-07-19T22:26:12.510+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 185 for task validate_features (name 'os' is not defined; 143)
[2025-07-19T22:26:12.545+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T22:26:12.555+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
