[2025-07-17T13:33:56.345+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T13:29:11.030802+00:00 [queued]>
[2025-07-17T13:33:56.356+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T13:29:11.030802+00:00 [queued]>
[2025-07-17T13:33:56.357+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2025-07-17T13:33:56.376+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_dataframe> on 2025-07-17 13:29:11.030802+00:00
[2025-07-17T13:33:56.393+0000] {standard_task_runner.py:60} INFO - Started process 11871 to run task
[2025-07-17T13:33:56.400+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'curated_market_dq', 'validate_dataframe', 'manual__2025-07-17T13:29:11.030802+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/curated_market_dq_dag.py', '--cfg-path', '/tmp/tmptafl5s4h']
[2025-07-17T13:33:56.402+0000] {standard_task_runner.py:88} INFO - Job 121: Subtask validate_dataframe
[2025-07-17T13:33:56.474+0000] {task_command.py:423} INFO - Running <TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T13:29:11.030802+00:00 [running]> on host 189e939b6cc2
[2025-07-17T13:33:56.674+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='curated_market_dq' AIRFLOW_CTX_TASK_ID='validate_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T13:29:11.030802+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T13:29:11.030802+00:00'
[2025-07-17T13:33:56.769+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-17T13:33:56.774+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-17T13:33:56.775+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T13:33:56.876+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-17T13:33:56.877+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-17T13:33:56.880+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T13:33:56.882+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T13:33:56.931+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/curated_market_dq_dag.py", line 74, in validate_dataframe
    batch_request = asset.build_batch_request(
TypeError: build_batch_request() got an unexpected keyword argument 'options'
[2025-07-17T13:33:56.951+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=curated_market_dq, task_id=validate_dataframe, execution_date=20250717T132911, start_date=20250717T133356, end_date=20250717T133356
[2025-07-17T13:33:56.973+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 121 for task validate_dataframe (build_batch_request() got an unexpected keyword argument 'options'; 11871)
[2025-07-17T13:33:57.028+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-17T13:33:57.066+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
