[2025-07-17T19:20:27.064+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T19:20:22.485222+00:00 [queued]>
[2025-07-17T19:20:27.067+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T19:20:22.485222+00:00 [queued]>
[2025-07-17T19:20:27.067+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-07-17T19:20:27.070+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_dataframe> on 2025-07-17 19:20:22.485222+00:00
[2025-07-17T19:20:27.074+0000] {standard_task_runner.py:60} INFO - Started process 401 to run task
[2025-07-17T19:20:27.075+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'curated_market_dq', 'validate_dataframe', 'manual__2025-07-17T19:20:22.485222+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/curated_market_dq_dag.py', '--cfg-path', '/tmp/tmpfl0puavx']
[2025-07-17T19:20:27.076+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask validate_dataframe
[2025-07-17T19:20:27.092+0000] {task_command.py:423} INFO - Running <TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T19:20:22.485222+00:00 [running]> on host b03a0574e2e2
[2025-07-17T19:20:27.134+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='curated_market_dq' AIRFLOW_CTX_TASK_ID='validate_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T19:20:22.485222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T19:20:22.485222+00:00'
[2025-07-17T19:20:27.152+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-17T19:20:27.152+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-17T19:20:27.153+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T19:20:27.164+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-17T19:20:27.164+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-17T19:20:27.164+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T19:20:27.164+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T19:20:27.182+0000] {validator.py:1461} INFO - 	7 expectation(s) included in expectation_suite.
[2025-07-17T19:20:27.211+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T19:20:27.211+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T19:20:27.212+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 4431.38it/s]
[2025-07-17T19:20:27.217+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 341.18it/s] 
[2025-07-17T19:20:27.217+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 494.20it/s]
[2025-07-17T19:20:27.223+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 265.73it/s]
[2025-07-17T19:20:27.224+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  30%|###       | 7/23 [00:00<00:00, 556.28it/s]
[2025-07-17T19:20:27.228+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  30%|###       | 7/23 [00:00<00:00, 413.54it/s]
[2025-07-17T19:20:27.233+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 1080.03it/s]
[2025-07-17T19:20:27.234+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 994.96it/s] 
[2025-07-17T19:20:27.234+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 988.81it/s]
[2025-07-17T19:20:27.235+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 983.32it/s]
[2025-07-17T19:20:27.479+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/curated_market_dq_dag.py", line 91, in validate_dataframe
    index_path = index_paths[0]                    # we only built one site
KeyError: 0
[2025-07-17T19:20:27.483+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=curated_market_dq, task_id=validate_dataframe, execution_date=20250717T192022, start_date=20250717T192027, end_date=20250717T192027
[2025-07-17T19:20:27.490+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40 for task validate_dataframe (0; 401)
[2025-07-17T19:20:27.520+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-17T19:20:27.529+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
